"""add_scraper_type_to_vendor_config

Revision ID: 884e61fb12eb
Revises: 0010_backup_addon
Create Date: 2026-04-26 16:23:22.287967

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '884e61fb12eb'
down_revision: Union[str, None] = '0010_backup_addon'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('extra_data', sa.Text(), nullable=True))
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_column('audit_logs', 'metadata')
    op.alter_column('backup_snapshots', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backup_snapshots', 'trigger',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backup_snapshots', 'product_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backup_snapshots', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backup_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_backup_snapshots_store_id'), 'backup_snapshots', ['store_id'], unique=False)
    op.create_index(op.f('ix_backup_snapshots_tenant_id'), 'backup_snapshots', ['tenant_id'], unique=False)
    op.alter_column('backup_subscriptions', 'plan',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backup_subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('backup_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('backup_subscriptions_tenant_id_key', 'backup_subscriptions', type_='unique')
    op.create_index(op.f('ix_backup_subscriptions_tenant_id'), 'backup_subscriptions', ['tenant_id'], unique=True)
    op.alter_column('jobs', 'skip_existing',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'locale',
               existing_type=sa.VARCHAR(length=5),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'email_confirmed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.add_column('vendor_configs', sa.Column('scraper_type', sa.String(length=50), nullable=False, server_default='auto'))
    op.alter_column('vendor_configs', 'scrape_scope',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_configs', 'scrape_scope',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pagina'::character varying"),
               existing_nullable=False)
    op.drop_column('vendor_configs', 'scraper_type')
    op.alter_column('users', 'email_confirmed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'locale',
               existing_type=sa.VARCHAR(length=5),
               server_default=sa.text("'en'::character varying"),
               existing_nullable=False)
    op.alter_column('jobs', 'skip_existing',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_index(op.f('ix_backup_subscriptions_tenant_id'), table_name='backup_subscriptions')
    op.create_unique_constraint('backup_subscriptions_tenant_id_key', 'backup_subscriptions', ['tenant_id'])
    op.alter_column('backup_subscriptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_subscriptions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('backup_subscriptions', 'plan',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'basic'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_backup_snapshots_tenant_id'), table_name='backup_snapshots')
    op.drop_index(op.f('ix_backup_snapshots_store_id'), table_name='backup_snapshots')
    op.alter_column('backup_snapshots', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('backup_snapshots', 'file_size_bytes',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('backup_snapshots', 'product_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.alter_column('backup_snapshots', 'trigger',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'manual'::character varying"),
               existing_nullable=False)
    op.alter_column('backup_snapshots', 'status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=False)
    op.add_column('audit_logs', sa.Column('metadata', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('audit_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('audit_logs', 'extra_data')
    # ### end Alembic commands ###
