"""credits_and_bulk_enhance

Revision ID: fd94ebca8374
Revises: 884e61fb12eb
Create Date: 2026-04-27 12:02:14.221006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd94ebca8374'
down_revision: Union[str, None] = '884e61fb12eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_enhance_subscriptions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('images_enhanced_this_month', sa.Integer(), nullable=False, server_default='0'),
    sa.Column('next_reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id')
    )
    op.create_table('credit_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=100), nullable=True),
    sa.Column('reference_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_transactions_tenant_id'), 'credit_transactions', ['tenant_id'], unique=False)
    op.add_column('tenants', sa.Column('credits_balance', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('tenants', sa.Column('images_enhanced_this_month', sa.Integer(), nullable=False, server_default='0'))
    op.alter_column('vendor_configs', 'scraper_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_configs', 'scraper_type',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'auto'::character varying"),
               existing_nullable=False)
    op.drop_column('tenants', 'images_enhanced_this_month')
    op.drop_column('tenants', 'credits_balance')
    op.drop_index(op.f('ix_credit_transactions_tenant_id'), table_name='credit_transactions')
    op.drop_table('credit_transactions')
    op.drop_table('bulk_enhance_subscriptions')
    # ### end Alembic commands ###
